### ISSUE TITLE
License

### ISSUE THREAD

**Issue by abriko** [orDaor/tic-tac-toe#1]
Hi @orDaor 

Nice see this fantastic project, we want use it as part of internal training demo.

Want check with you, this repo is what license?

Thanks.

**Comment by orDaor** [comment]
> Hi @orDaor
> 
> Nice see this fantastic project, we want use it as part of internal training demo.
> 
> Want check with you, this repo is what license?
> 
> Thanks.

Hi! I am happy you appreciate my project. License is ISC, therefore you can use it for your purpose.

**Comment by abriko** [comment]
Thank you,

Cheers.
