### ISSUE TITLE
install guide?

### ISSUE THREAD

**Issue by bharal** [orDaor/tic-tac-toe#2]
there is a lot of architecture and design stuff in the readme, but how do i actually run this locally after getting the code?

**Comment by orDaor** [comment]
Hi! After cloning the repo, move onto the project root directory and just run
`npm install`
to install packages for the project.

Then start the node server with nodemon (live reload feature) on port 3000
`npm start`
Or simply run
`node app.js`

To locally serve the web page enter in the browser
`http://localhost:3000`
